title: Even Better Specs
description: Guidelines for maintainable specs
theme: just-the-docs

url: https://evenbetterspecs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
