title: Even Better Specs
description: Guidelines for readable and maintainable tests
theme: just-the-docs

url: https://evenbetterspecs.github.io

aux_links:
  GitHub: https://github.com/evenbetterspecs/evenbetterspecs.github.io

# External navigation links
nav_external_links:
  # - title: What is it
  #   url: "#what-is-it"
  #   hide_icon: true
  # - title: Guiding principles
  #   url: "#guiding-principles"
  #   hide_icon: true
  - title: Describe what you are testing
    url: "#describe"
    hide_icon: true
  - title: Use contexts
    url: "#use-contexts"
    hide_icon: true
  - title: Short description
    url: "#short-description"
    hide_icon: true
  - title: Group expectations
    url: "#group-expectations"
    hide_icon: true
  - title: All possible cases
    url: "#all-possible-cases"
    hide_icon: true
  - title: Expect vs should
    url: "#expect-vs-should"
    hide_icon: true
  - title: Let's not
    url: "#lets-not"
    hide_icon: true
  - title: Avoid hooks
    url: "#avoid-hooks"
    hide_icon: true
  - title: Don't use shared examples
    url: "#dont-use-shared-examples"
    hide_icon: true
  - title: Mock external dependencies
    url: "#mock-external-dependencies"
    hide_icon: true
  - title: Stub HTTP requests
    url: "#stub-http-requests"
    hide_icon: true
  - title: Create only the data you need
    url: "#create-only-the-data-you-need"
    hide_icon: true
